config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :places, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :units, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :producers, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :wines, only: [:new, :create, :index, :update, :show, :edit, :update, :destroy]
  resources :bottles, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :merchants, only: [:create, :index, :destroy]
  resources :invoices, only: [:create, :index, :destroy]
  resources :storinvoices, only: [:create, :index, :destroy]
  resources :critics, only: [:create, :index, :destroy]
  resources :reviews, only: [:create, :index, :destroy]

  get 'accessibility', to: 'pages#accessibility', as: :accessibility
  get 'about', to: 'pages#about', as: :about
  get 'privacy', to: 'pages#privacy', as: :privacy
  get 'settings', to: 'pages#settings', as: :settings
  get 'latest', to: 'pages#latest', as: :latest
  get 'other', to: 'pages#other', as: :other

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="light text-black justify-content-center overflow-hidden sticky-bottom">

  <div class="row">
    <div class="col">
      <p class="text-center pt-3">
        <%= link_to "Home", root_path, class:"text-reset text-danger" %>
         | 
        <%= link_to "About us", about_path, class:"text-reset text-danger" %>
         | 
        <%= link_to "Privacy & Cookies", privacy_path, class:"text-reset text-danger" %>
         | 
        © 2020
      </p>
    </div>
  </div>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark d-flex justify-content-between sticky-top">

  <div class="p-2 bd-highlight text-white">
    <%= link_to root_path do %>
      <%# <%= image_tag("desk-dash-logo.png", class: "logo") %>
    <% end %>
  </div>

  <div class="d-flex">

    <li class="nav-item">
      <%= link_to "Home", root_path, class: "nav-link text-white" %>
    </li>

    <li class="nav-item">
      <%= link_to "Latest", latest_path, class: "nav-link text-white" %>
    </li>
  
    <li class="nav-item">
      <%= link_to "Storages", places_path, class: "nav-link text-white" %>
    </li>

    <li class="nav-item">
      <%= link_to "Cellar Overview", wines_path, class: "nav-link text-white" %>    
    </li>

    <li class="nav-item">
      <%= link_to "Other Wines", other_path, class: "nav-link text-white" %>
    </li>

    <li class="nav-item">
      <%= link_to "Functions", "#", class: "nav-link text-white" %>
    </li>
    
    <li class="nav-item">
      <%= link_to "Settings", settings_path, class: "nav-link text-white" %>    
    </li>

    <%= form_tag places_path, class: "form-inline my-2 my-lg-0 mr-3", method: :get do %>
      <%= text_field_tag :query,
                         params[:query],
                         class: "form-control mr-sm-2",
                         placeholder: "Search"
      %>
      <%= submit_tag "Search", class: "btn btn-outline-light my-2 my-sm-0" %>
    <% end %>

    <div class="p-1 bd-highlight dropdown">
    
      <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user-circle text-white" style="font-size: 30px"></i>
      </button>
      
      <div class="dropdown-menu dropdown-menu-lg-right" aria-labelledby="dropdownMenuButton">
        <% if user_signed_in? %>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <%= link_to 'View storages', places_path, class: "dropdown-item" %>
          <a class="dropdown-item" href="#">Leave a review</a>
        <% else %>
          <%= link_to 'Sign in', new_user_session_path, class: "dropdown-item" %>
          <%= link_to 'Register', new_user_registration_path, class: "dropdown-item" %>
        <% end %>
      </div>
    
    </div>
  
  </div>

</nav>