config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :places, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :units, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :producers, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :wines, only: [:new, :create, :index, :update, :show, :edit, :update, :destroy]
  resources :bottles, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :merchants, only: [:create, :index, :destroy]
  resources :invoices, only: [:create, :index, :destroy]
  resources :storinvoices, only: [:create, :index, :destroy]
  resources :critics, only: [:create, :index, :destroy]
  resources :reviews, only: [:create, :index, :destroy]

  get 'accessibility', to: 'pages#accessibility', as: :accessibility
  get 'about', to: 'pages#about', as: :about
  get 'privacy', to: 'pages#privacy', as: :privacy
  get 'settings', to: 'pages#settings', as: :settings
  get 'latest', to: 'pages#latest', as: :latest
  get 'other', to: 'pages#other', as: :other

end

app/views/pages/about.html.erb
<p> About us </p>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(354deg, rgba(179,174,238,0.6964986678265056) 0%, rgba(148,187,233,1) 100%), url()">
  <div class="containter overflow-hidden">
    <div class="row">
      <div class="col col-md-3">
      </div>
      <div class="col col-md-6 col-sm-10 text-white py-5">
        <h1 class="display-6">Welcome to Automated Cellar</h1>
        <p class="lead">Focus on enjoying wine, not managing the cellar</p>
        <p>Automated Cellar is an ambitious start-up bringing automation to the management of a wine cellar for collectors and professionals with several cellars or several storages.</p>
        <hr class="my-4">
        <%= link_to places_path do %>
          <button class="btn btn-primary" data-turbolinks="false">Register for free</button>
        <% end %>
      </div>
      <div class="col col-md-3">
      </div>
    </div>
  </div>
</div>

<div class="container my-5">
  
  <div class="row align-items-center">
    <div class="col col-md-1">
    </div>
    <div class="col col-md-5 col-sm-10 my-5">
      <h2>How does the automation work ?</h2>
      <p> Automatisation works when the wine enters the cellar:</p>
      <p>Enter your login and password. This is exactly what you would to set-up your mailboxes on your smartphone.</p>
      <p>Wine stored in professional storages or merchants' reserves are downloaded automatically once you have stored your login credentials </p>
      <% if !user_signed_in? %>
        <%= link_to new_user_session_path do %>
          <button class="btn btn-dark">Sign in</button>
        <% end %>
       <% else %>
       <%= link_to places_path do %>
          <button class="btn btn-primary" data-turbolinks="false">Register for free</button>
       <% end %>
      <% end %>
    </div>
    <div class="col col-md-5 col-sm-10">
      <img src=""
           alt=""
           width="100%"
           class="shadow rounded"
           >
    </div>
    <div class="col col-md-1">
    </div>
  </div>

  <hr>

  <div class="row align-items-center">
    <div class="col col-md-1">
    </div>
    <div class="col col-md-5 col-sm-10 my-5">
      <img src=""
                alt=""
                width="100%"
                class="shadow rounded"
              >
     </div>
    <div class="col col-md-5 col-sm-10 my-5">
      <h2>Upload an invoice and the app will extract the data for your validation</h2>
      <p>We have tried to fix what we thought was wrong with other wine cellar management softwares.</p>
    </div>
     <div class="col col-md-1">
     </div>
  </div>

  <hr>

  <div class="row align-items-center">
    <div class="col col-md-1">
    </div>
    <div class="col col-sm-12 my-md-5">
      <h2 class="text-center">The app enables to view the position of the bottles in wine racks or a wine fridge and move it so the app corresponds to the situation in the cellar.</h2>
      <div class="d-flex justify-content-center my-3">
        <%# <% @places.each do |place| %>
        <%# 
          <div class="card mx-md-3 mx-sm-1 mt-3" style="width: 18rem;">
            <img src="<%= place.photo class="card-img-top" %>
            <%# <div class="card-body">
              <h5 class="card-title"><%= place.name %></h5>
              <%# <%= link_to "More info", place_path(place), class: "btn btn-primary" %>

            <%# </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col col-md-1">
    </div>
  </div>

  <hr>

  <div class="row align-items-center">
    <div class="col col-md-1">
    </div>
    
    <div class="col col-sm-10 my-5">
    <h2 class="text-center">What we are and we are not</h2>
      <div class="d-flex flex-column justify-content-center my-3">
        
        <div class="row mt-3">
          <div class="col col-2">
            <i class="fas fa-wifi" style="font-size: 50px"></i>
          </div>
          <div class="col">
            <p>This is a wine management tool of the modern digital age for amateurs and sommeliers with multiple cellars.</p>
          </div>
        </div>

        <div class="row mt-3">
          <div class="col col-2">
            <i class="fas fa-mug-hot" style="font-size: 50px"></i>
          </div>
          <div class="col">
            <p>We are not a software company and not selling a software that you need to input data into. We are selling a tool that saves time by automation. Wine data dissimenated on the web is fetched and consolidated it in one place. We are not selling a wine database, we offer the tools to find the information.</p>
          </div>

      </div>

      <div class="row mt-3">
        <div class="col col-2">
          <i class="fas fa-desktop" style="font-size: 50px"></i>
        </div>
        <div class="col">
          <p>Automated cellar </p>
        </div>
      </div>

      <div class="row mt-5 justify-content-center">
      <%= link_to places_path do %>
        <button class="btn btn-primary" data-turbolinks="false">Register for free</button>
      <% end %>
      </div>

    </div>
  </div>

  <div class="col col-md-1">
  </div>

</div>

app/views/pages/latest.html.erb
<p> Latest movements in the cellar </p>
<p> Latest tasks, checks and operations  performed by the site </P>

app/views/pages/other.html.erb
<div class="container">

    <div class="border border-primary justify-content-center">
    <h2> Wines tasted (never entered the cellar) </h2>
    </div>

    <div class="border border-danger">
            <table class="table-sm table-striped table-hover">
            <thead>
                <tr>
                <th scope="col"> Wines </th>
                <th scope="col"> Vintages </th>
                <th scope="col"> Tasted </th>
                </tr>
            </thead>
                <tbody>
                    <tr>
                        <td>  DRC Romanee Conti</td>
                        <td>  2009, 2010, 2011, 2012, 2014, 2015</td>
                        <td> n bottles, y tasting notes </td>
                    </tr>
                        <td>  </td>
            </tbody>
            </table>
        </div>

    <div class="border border-primary justify-content-center">
    <h2> Wines which have left the cellar </h2>
    </div>

    <div class="border border-danger">
            <table class="table-sm table-striped table-hover">
            <thead>
                <tr>
                <th scope="col"> Wines </th>
                <th scope="col"> Vintages </th>
                <th scope="col"> Tasted </th>
                </tr>
            </thead>
                <tbody>
                    <tr>
                        <td>  </td>
                        <td>  </td>
                        <td>  </td>
                    </tr>
                        <td>  </td>
            </tbody>
            </table>
        </div>

</div>

app/views/pages/settings.html.erb
<div class="container">

    <div class="border border-danger">
        <table class="table-sm table-striped table-hover">
        <thead>
            <tr>
            <th scope="col"> Type </th>
            <th scope="col"> Action </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td> Remote Cellars </td>
                <td> Login details </td>
            </tr>
            <tr>
                <td> Subscriptions </td>
                <td> Login details </td>
            </tr>
            <tr>
                <td> Social Media </td>
                <td> Login details </td>
            </tr>
            <tr>
                <td> Local Cellars  </td>
                <td> <%= link_to "Add", new_place_path(@place), class: "btn btn-outline-secondary" %>
                <%= link_to "Remove", method: :delete,  data: { confirm: "Are you sure?"}, class: "btn btn-outline-secondary" %> </td>
            </tr>
            <tr>
                <td> Cases </td>
                <td> <%= link_to "Add", new_unit_path(@place), class: "btn btn-outline-secondary" %></td>
            </tr>
            <tr>
                <td> Wine fridges </td>
                <td> <%= link_to "Add", new_unit_path(@place), class: "btn btn-outline-secondary" %></td>
            </tr>
            <tr>
                <td> Wine Racks </td>
                <td> <%= link_to "Add", new_unit_path(@place), class: "btn btn-outline-secondary" %> </td>
            </tr>
            <tr>   
                <td> Producers  </td>
                <td> <%= link_to "Add", new_producer_path(@producer), class: "btn btn-outline-secondary" %> </td>
            </tr>
            <tr>
                <td> Wines  </td>
                <td> <%= link_to "Add", new_wine_path(@wine), class: "btn btn-outline-secondary" %> </td>
            </tr>
            <tr>
                <td> Bottles  </td>
                <td> <%= link_to "Add", new_bottle_path(@bottle), class: "btn btn-outline-secondary" %> </td>
            </tr>
            <tr>
                <td> Default page  </td>
                <td>  </td>
            </tr>
            </tbody>
        </table>
    </div>

</div>