config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :places, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :units, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :producers, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :wines, only: [:new, :create, :index, :update, :show, :edit, :update, :destroy]
  resources :bottles, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :merchants, only: [:create, :index, :destroy]
  resources :invoices, only: [:create, :index, :destroy]
  resources :storinvoices, only: [:create, :index, :destroy]
  resources :critics, only: [:create, :index, :destroy]
  resources :reviews, only: [:create, :index, :destroy]

  get 'accessibility', to: 'pages#accessibility', as: :accessibility
  get 'about', to: 'pages#about', as: :about
  get 'privacy', to: 'pages#privacy', as: :privacy
  get 'settings', to: 'pages#settings', as: :settings
  get 'latest', to: 'pages#latest', as: :latest
  get 'other', to: 'pages#other', as: :other

end

app/models/producer.rb
class Producer < ApplicationRecord
    has_many :wines
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController

    def index
    @producers = Producer.all
    end

    def show
    set_producer
    end

    def new
    @producer = Producer.new
    end

    def create
    @producer = Producer.new(producer_params)
    if @producer.save
        redirect_to producers_path
    else
        render :new
    end
    end

    def edit
    set_producer
    end

    def update
    set_producer
    if @producer.update(producer_params)
    flash.alert = 'Producer updated successfully'
    redirect_to producers_path
    else
    flash.alert = 'There was an error updating producer'
    render :edit
    end
    end

    def destroy
    set_producer
    if @producer.destroy
    flash.notice = 'Producer deleted successfully'
    redirect_to producers_path
    else
    flash.notice = 'There was an error deleting this producer'
    end
    end

    private

    def set_producer
    @producer = Producer.find(params[:id])
    end
    
    def producer_params
        params.require(:producer).permit(
          :name)
    end

end

app/views/producers/edit.html.erb
<div class="container">
  <div class="border border-danger">
    <%= simple_form_for(@producer) do |f| %>
    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>
    <%= f.submit %>
    <% end %>
   </div>
</div>

app/views/producers/index.html.erb
<div class="container">

    <div>
    <%= link_to "Add a Producer", new_producer_path(@producer), class: "btn btn-outline-secondary" %>
    </div>

    <div class="border border-danger">
        <table class="table-sm table-striped table-hover">
        <thead>
            <tr>
            <th scope="col"> Producer </th>
            <th scope="col"> Actions </th>
            </tr>
        </thead>
            <tbody>
            <tr>
            <% @producers.each do |producer| %>
            <td> <%= producer.name %> </td>
            <td>
            <%= link_to "Update", edit_producer_path(producer), class: "btn btn-outline-secondary" %>
            <%= link_to "Remove", producer_path(producer), method: :delete,  data: { confirm: "Are you sure?"}, class: "btn btn-outline-secondary" %> 
            </td>
            </tr>
            <% end %>
            </tbody>
        </table>
    </div>

<div>

app/views/producers/new.html.erb
<div class="container">
    <div class="border border-danger">
        <div class="col-12 col-md-6 offset-md-3">
            <%= simple_form_for (@producer) do |f| %>
            <div>
            <%= f.label :name %>
            <%= f.text_field :name %>
            </div>
            <%= f.submit %>
            <% end %>
        </div>
    </div>
</div>