config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :places, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :units, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :producers, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :wines, only: [:new, :create, :index, :update, :show, :edit, :update, :destroy]
  resources :bottles, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :merchants, only: [:create, :index, :destroy]
  resources :invoices, only: [:create, :index, :destroy]
  resources :storinvoices, only: [:create, :index, :destroy]
  resources :critics, only: [:create, :index, :destroy]
  resources :reviews, only: [:create, :index, :destroy]

  get 'accessibility', to: 'pages#accessibility', as: :accessibility
  get 'about', to: 'pages#about', as: :about
  get 'privacy', to: 'pages#privacy', as: :privacy
  get 'settings', to: 'pages#settings', as: :settings
  get 'latest', to: 'pages#latest', as: :latest
  get 'other', to: 'pages#other', as: :other

end

app/models/place.rb
class Place < ApplicationRecord
    has_many :units
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  before_action :set_place, only: %i[show edit update destroy]
  before_action :place_params, only: %i[create update]
  
  require 'open-uri'
  require 'nokogiri'
  require 'mechanize'
  require 'csv'
  
  def index
    @places = Place.all
    places_overview
  end

  def show
    set_place
    place_overview(@place)
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    @place.user_id = current_user.id
    if @place.save
      redirect_to places_path
    else
      render :new
    end
  end

  def edit
    set_place
  end

  def update
    set_place
    if @place.update(place_params)
    flash.alert = 'Place updated successfully'
    redirect_to places_path
    else
    flash.alert = 'There was an error updating place'
    render :edit
    end
  end

  def destroy
    set_place
    if @place.destroy
    flash.notice = 'Place deleted successfully'
    redirect_to places_path
    else
    flash.notice = 'There was an error deleting this place'
    end
  end

  private

  def places_overview
    places_overview = []
    @places.each do |place|
      places_overview.push(place_overview(place))
    end
    @places_overview = places_overview
  end

  def place_overview(place)
    @place = place
    place_overview = []
    place_overview.push(@place)
    place_overview.push(price_paid(place))
    place_overview
  end
  
  def price_paid(place)
    @place = place
    price_paid = 0
    @place.units.each do |unit|
      price_paid += price_paid_unit(unit)
    end
    price_paid
  end

  def price_paid_unit(unit)
    @unit = unit
    price_paid_unit = 0
      @unit.bottles.each do |bottle|
      price_paid_unit += bottle.pre_tax_cost.to_f if bottle.tax_status = "IB"
      price_paid_unit += bottle.post_tax_cost.to_f if bottle.tax_status = "DP"
    end
    price_paid_unit
  end
  helper_method :price_paid_unit

  def set_place
    @place = Place.find(params[:id])
  end

  def place_params
    params.require(:place).permit(
      :id,
      :user_id,
      :name,
      :account_number,
      :address)
  end

  # def login_to_website
  #   email = "bob@me.com"
  #   password = "secure_pass5!" 
  #   mechanize = Mechanize.new
  #   url = 'http://www.local-response.xyz/users/sign_in'
  #   login_page = mechanize.get url
  #   # Click the login link
  #   # login_page = mechanize.click(page.link_with(text: /Log In/))
  #   # submit the login form
  #   form = login_page.forms.first
  #   form.field_with(id: "email").value = email
  #   form.field_with(id: "password").value = password
  #   form.submit
  # end

  # def import_from_website
  #   # 1. Fetch the data stored in this place 
  #   url = "http://www.local-response.xyz/bookings"
  #   search_results = []
  #   html_doc = Nokogiri::HTML(open(url), nil, 'utf-8')
  #   html_doc.search('.bookings-index').first(5).each do |element|
  #   raise
  #     # element.text.strip
  #   # puts element.attribute('href').value
  #   end
  #   # 2. Store the search results
  # end

  # def download_csv
  #   url =  ""
  #   download = open(url)
  #   IO.copy_stream(download, 'test.csv')
  #   CSV.new(download).each do |l|
  #     puts l
  #   end
  # end

  # def load_csv
  #   CSV.foreach(@csv_file) do |row|
  #     @recipes << Recipe.new(row[0], row[1])
  #   end
  # end

  # def save_to_csv
  #   CSV.open(@csv_file, 'wb') do |csv|
  #     @recipes.each do |recipe|
  #       csv << [recipe.name, recipe.description]
  #     end
  #   end
  # end

  # this method will return true if there is at least one professional storage
  
end

app/views/places/edit.html.erb
<div class="container">
  <div class="border border-danger">
    <%= simple_form_for(@place) do |f| %>
    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>
    <div>
    <%= f.label :account_number %>
    <%= f.text_field :account_number %>
    </div>
    <div>
    <%= f.label :address %>
    <%= f.text_field :address %>
    </div>
    <%= f.submit %>
    <% end %>
   </div>
</div>

app/views/places/index.html.erb
<div class="container">

    <% if any_non_professional_storage? %>
    <h2> Local Cellars </h2>
    <div class="border border-danger">
        <table class="table-sm table-striped table-hover">
        <thead>
            <tr>
            <th scope="col"> Storage name </th>
            <th scope="col"> Wines </th>
            <th scope="col"> Price Paid </th>
            <th scope="col"> Value </th>
            <th scope="col"> Difference </th>
            <th scope="col"> Actions </th>
            </tr>
        </thead>
            <tbody>
            <% @places_overview.each do |place_overview| %>
                <tr>
                    <% if !place_overview[0].professional? %>
                    <td> <%= link_to place_overview[0].name, place_path(place_overview[0]) %> </td>
                    <td>   </td>
                    <td>  <%= place_overview[1] %></td>
                    <td>  </td>
                    <td>  </td>
                    <td> <%= link_to 'Update', edit_place_path(place_overview[0]), class: "btn btn-outline-secondary"%>
                    <%= link_to "Remove", place_path(@place), method: :delete,  data: { confirm: "Are you sure?"}, class: "btn btn-outline-secondary" %>
                    </td>
                    </tr>
                    <% end %>
            <% end %>
        </tbody>
        </table>
    </div>
    <% end %>

    <% if any_professional_storage? %>
    <h2> Remote Cellars </h2>
    <div class="border border-danger">
        <table class="table-sm table-striped table-hover">
        <thead>
            <tr>
            <th scope="col"> Storage name </th>
            <th scope="col"> Wines </th>
            <th scope="col"> Price Paid </th>
            <th scope="col"> Value </th>
            <th scope="col"> Difference </th>
            <th scope="col"> Action </th>
            </tr>
        </thead>
            <tbody>
            <% @places_overview.each do |place_overview| %>
                <tr>
                    <% if place_overview[0].professional? %>
                    <td> <%= link_to place_overview[0].name, place_path(place_overview[0]) %> </td>
                    <td>  </td>
                    <td> <%= place_overview[1] %></td>
                    <td>  </td>
                    <td>  </td>
                    <td> <%= link_to 'Update', edit_place_path(place_overview[0]), class: "btn btn-outline-secondary"%> </td>
                </tr>
                    <% end %>
            <% end %>
        </tbody>
        </table>
    </div>
    <% end %>

    <div class="border border-primary justify-content-center">
    <h2> Map (on/off) </h2>
    </div>

</div>

app/views/places/new.html.erb
<div class="container">
  <div class="border border-danger">
    <div class="row">
        <div class="col-xs-12 col-sm-4 mx-auto form-login mb-5">
        <%= simple_form_for (@place) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :account_number %>
        <%= f.text_field :account_number %>
        <%= f.label :address %>
        <%= f.text_field :address %>
        <%= f.submit %>
        <% end %>
         </div>
    </div>
  </div>
</div>

app/views/places/show.html.erb
<div class="container">

<%= link_to "Back to all storages", places_path, class: "btn btn-outline-secondary" %>
<h2> <%= @place.name %> </h2>

    <% if @place.professional? %>
    <div class="border border-danger">
        <table class="table-sm table-striped table-hover">
        <thead>
            <tr>
            <th scope="col"> Rotation </th>
            <th scope="col"> Tax Status </th>
            <th scope="col"> Bottles </th>
            <th scope="col"> Packaging </th>
            <th scope="col"> Wine </th>
            <th scope="col"> Vintage </th>
            <th scope="col"> Price paid </th>
            <th scope="col"> Value </th>
            </tr>
        </thead>
            <tbody>
            <% @place.units.each do |unit| %>
                <% @unit = unit %>
                    <tr>
                    <td> <%= @unit.rotation %> </td>
                    <td> <%= @unit.tax_status %> </td>
                    <td> <%= @unit.bottles_inside %> </td>
                    <td> <%= @unit.capacity%>b <%= 'owc' if @unit.owc %> <%= 'oc' if @unit.oc %></td>
                    <td> <%= @unit.bottles.first.wine.name %> </td>
                    <td> <%= @unit.bottles.first.vintage %> </td>
                    <td> <%= price_paid_unit(@unit) %> </td>
                    <td>  </td>
                    </tr>
            <% end %>
        </tbody>
        </table>
    </div >
    <%end%>

    <% if !@place.professional? %>
        <% @place.units.each do |unit| %>
            <% @unit = unit %>
            
            <% if unit.fridge? %>
                <div class="border border-danger"> 
                <h3> <%= @unit.name %> </h3>
                <h3> <%= @unit.bottles_inside %> bottles </h3>
                <h3> <%= @unit.capacity - @unit.bottles_inside %> empty spaces </h3>
                <table class="table-sm table-striped table-hover">
                <thead>
                <tr>
                <th scope="col"> hb </th>
                <th scope="col"> b </th>
                <th scope="col"> M </th>
                <th scope="col"> DM </th>
                <th scope="col"> Name </th>
                <th scope="col"> Vintage </th>
                <th scope="col"> Date in </th>
                <th scope="col"> Original Value </th>
                <th scope="col"> Latest Value </th>
                <th scope="col"> Actions </th>
                </tr>
                </thead>
                <tbody>
                <% @unit.bottles.each do |bottle| %>
                <% @bottle = bottle %>
                <tr>
                <td> <%= bottle.number if bottle.half_bottle? %> </td>
                <td> <%= bottle.number if bottle.bottle? %> </td>
                <td> <%= bottle.number if bottle.magnum? %> </td>
                <td> <%= bottle.number if bottle.double_magnum? %> </td>
                <td> <%= bottle.wine.name %> </td>
                <td> <%= bottle.vintage %> </td>
                <td> <%= bottle.date_in %> </td>
                <td> <%= bottle.post_tax_cost %> </td>
                <td> <%= link_to 'Update', edit_bottle_path(@bottle), class: "btn btn-outline-secondary"%> 
                 <%= link_to 'Drink', edit_bottle_path(@bottle), class: "btn btn-outline-secondary"%>
                 <%= link_to 'Sale', edit_bottle_path(@bottle), class: "btn btn-outline-secondary"%>
                <%= link_to 'Transfer', edit_bottle_path(@bottle), class: "btn btn-outline-secondary"%>
                </td>
                </tr>
                <% end %>
                </tbody>
                </table>
                </div>

            <% elsif unit.rack? %> 
                <div class="border border-danger">
                <h3> <%= @unit.name %> </h3>
                <h3> <%= @unit.bottles_inside %> bottles </h3>
                <h3> <%= @unit.capacity - @unit.bottles_inside %> empty spaces </h3>
                <table class="table-sm table-striped table-hover">
                <thead>
                <tr>
                <th scope="col"> hb </th>
                <th scope="col"> b </th>
                <th scope="col"> M </th>
                <th scope="col"> DM </th>
                <th scope="col"> Name </th>
                <th scope="col"> Vintage </th>
                <th scope="col"> Date in </th>
                <th scope="col"> Original Value </th>
                <th scope="col"> Latest Value </th>
                <th scope="col"> Actions </th>
                </tr>
                </thead>
                <tbody>
                <% @unit.bottles.each do |bottle| %>
                <% @bottle = bottle %>  
                <tr>
                <td> <%= bottle.number if bottle.half_bottle? %> </td>
                <td> <%= bottle.number if bottle.bottle? %> </td>
                <td> <%= bottle.number if bottle.magnum? %> </td>
                <td> <%= bottle.number if bottle.double_magnum? %> </td>
                <td> <%= bottle.wine.name %> </td>
                <td> <%= bottle.vintage %> </td>
                <td> <%= bottle.date_in %> </td>
                <td> <%= bottle.post_tax_cost %> </td>
                <td>  </td>
                <td> <%= link_to 'Update', edit_bottle_path(@bottle), class: "btn btn-outline-secondary"%> 
                 <%= link_to 'Drink', edit_bottle_path(@bottle), class: "btn btn-outline-secondary"%>
                 <%= link_to 'Sale', edit_bottle_path(@bottle), class: "btn btn-outline-secondary"%>
                <%= link_to 'Transfer', edit_bottle_path(@bottle), class: "btn btn-outline-secondary"%>
                </td>
                </tr>
                <% end %>
                </tbody>
                </table>
                <%= link_to "Add Bottles", new_bottle_path(@bottle), class: "btn btn-outline-secondary" %>
                </div>

            <% elsif unit.packaging? %>
                <div class="border border-danger">
                <h3> Cases </h3>
                <h3>  </h3>
                <table class="table-sm table-striped table-hover">
                <thead>
                <tr>
                <th scope="col"> hb </th>
                <th scope="col"> b </th>
                <th scope="col"> M </th>
                <th scope="col"> DM </th>
                <th scope="col"> Name </th>
                <th scope="col"> Vintage </th>
                <th scope="col"> Date in </th>
                <th scope="col"> Original Value </th>
                <th scope="col"> Latest Value </th>
                <th scope="col"> Actions </th>
                </tr>
                </thead>
                <tbody>
                <% @unit.bottles.each do |bottle| %>
                <% @bottle = bottle %>  
                <tr>
                <td> <%= bottle.number if bottle.half_bottle? %> </td>
                <td> <%= bottle.number if bottle.bottle? %> </td>
                <td> <%= bottle.number if bottle.magnum? %> </td>
                <td> <%= bottle.number if bottle.double_magnum? %> </td>
                <td> <%= bottle.wine.name %> </td>
                <td> <%= bottle.vintage %> </td>
                <td> <%= bottle.date_in %> </td>
                <td> <%= bottle.post_tax_cost %> </td>
                <td>  </td>
                <td> <%= link_to 'Update', edit_bottle_path(@bottle), class: "btn btn-outline-secondary"%> 
                 <%= link_to 'Drink', edit_bottle_path(@bottle), class: "btn btn-outline-secondary"%>
                 <%= link_to 'Sale', edit_bottle_path(@bottle), class: "btn btn-outline-secondary"%>
                <%= link_to 'Transfer', edit_bottle_path(@bottle), class: "btn btn-outline-secondary"%>
                </td>
                </tr>
                <% end %>
                </tbody>
                </table>
                <%= link_to "Add Bottles", new_bottle_path(@bottle), class: "btn btn-outline-secondary" %>
                </div>

            <% elsif !unit.packaging? %>
                <div class="border border-danger">
                <h3> Bottles </h3>
                <table class="table-sm table-striped table-hover">
                <thead>
                <tr>
                <th scope="col"> hb </th>
                <th scope="col"> b </th>
                <th scope="col"> M </th>
                <th scope="col"> DM </th>
                <th scope="col"> Name </th>
                <th scope="col"> Vintage </th>
                <th scope="col"> Date in </th>
                <th scope="col"> Original Value </th>
                <th scope="col"> Latest Value </th>
                <th scope="col"> Actions </th>
                </tr>
                </thead>
                <tbody>
                <% @unit.bottles.each do |bottle| %>
                <% @bottle = bottle %>  
                <tr>
                <td> <%= bottle.number if bottle.half_bottle? %> </td>
                <td> <%= bottle.number if bottle.bottle? %> </td>
                <td> <%= bottle.number if bottle.magnum? %> </td>
                <td> <%= bottle.number if bottle.double_magnum? %> </td>
                <td> <%= bottle.wine.name %> </td>
                <td> <%= bottle.vintage %> </td>
                <td> <%= bottle.date_in %> </td>
                <td> <%= bottle.post_tax_cost %> </td>
                <td>  </td>
                <td> <%= link_to 'Update', edit_bottle_path(@bottle), class: "btn btn-outline-secondary"%> 
                 <%= link_to 'Drink', edit_bottle_path(@bottle), class: "btn btn-outline-secondary"%>
                 <%= link_to 'Sale', edit_bottle_path(@bottle), class: "btn btn-outline-secondary"%>
                <%= link_to 'Transfer', edit_bottle_path(@bottle), class: "btn btn-outline-secondary"%>
                </td>
                </tr>
                <% end %>
                </tbody>
                </table>
                <%= link_to "Add Bottles", new_bottle_path(@bottle), class: "btn btn-outline-secondary" %>
                </div>

            <% end %>

        <% end %>
    <%end%>

</div>